# -*- mode: python; -*-
# 
Import('env')

src_files = Split("""
                     ../../graphsql/server/gstore/cmdline/cmdhelper.cpp
					 ../../graphsql/server/gstore/cfg/datatypes.cpp
					 ../../graphsql/server/gstore/sql_dispatcher/dispatcher.cpp
					 ../../graphsql/server/gstore/sql_dispatcher/evl_materize_view.cpp
					 ../../graphsql/server/gstore/parser_api/parser_api.cpp
					 ../../graphsql/server/gstore/sql_dispatcher/evaluator.cpp
					 ../../graphsql/server/gstore/sql_dispatcher/resolver.cpp
					 ../../graphsql/server/gstore/session/session.cpp
					 ../../graphsql/server/parser/value.cpp
					 ../../graphsql/server/parser/graph_sql_parser.cpp
					 ../../graphsql/server/parser/graph_sql_parser.tab.cpp
					 ../../graphsql/server/lib/process.cpp                     
					 gse_udf_demo.cpp
					""")

gse_udf_build = env.Program(target='gse_udf_demo', source=src_files)
Return ("gse_udf_build")
