EdgeTypes: 
- EdgeId: 0
  EdgeName: vote
  FromVertexTypeName: person
  IsDirected: false
  ToVertexTypeName: person
GraphConfigVersion: 1
GraphId: 0
GraphName: wiki_vote
SegSizeInBits: 20
VertexTypes: 
- PrimaryId: 
    AttributeName: id
    AttributeType: UINT
  VertexId: 0
  VertexName: person
  VertexStatisticsType: 1
