EdgeTypes: 
- EdgeId: 0
  FromVertexTypeName: '*'
  IsDirected: false
  Name: transtoentity
  ToVertexTypeName: '*'
GraphConfigVersion: 1
GraphId: 0
GraphName: lianlian
SegSizeInBits: 20
VertexTypes: 
- Attributes: 
  - AttributeName: isFraudulent
    AttributeType: BOOL
  - AttributeName: label
    AttributeType: STRING
  Name: transaction
  PrimaryId: 
    AttributeName: value
    AttributeType: STRING
    Nullable: false
  VertexId: 0
  VertexStatisticsType: 1
- Attributes: 
  - AttributeName: isFraudulent
    AttributeType: BOOL
  - AttributeName: label
    AttributeType: STRING
  Name: userid
  PrimaryId: 
    AttributeName: value
    AttributeType: STRING
    Nullable: false
  VertexId: 1
  VertexStatisticsType: 1
- Attributes: 
  - AttributeName: isFraudulent
    AttributeType: BOOL
  - AttributeName: label
    AttributeType: STRING
  Name: ssn
  PrimaryId: 
    AttributeName: value
    AttributeType: STRING
    Nullable: false
  VertexId: 2
  VertexStatisticsType: 1
- Attributes: 
  - AttributeName: isFraudulent
    AttributeType: BOOL
  - AttributeName: label
    AttributeType: STRING
  Name: bankid
  PrimaryId: 
    AttributeName: value
    AttributeType: STRING
    Nullable: false
  VertexId: 3
  VertexStatisticsType: 1
- Attributes: 
  - AttributeName: isFraudulent
    AttributeType: BOOL
  - AttributeName: label
    AttributeType: STRING
  Name: cell
  PrimaryId: 
    AttributeName: value
    AttributeType: STRING
    Nullable: false
  VertexId: 4
  VertexStatisticsType: 1
- Attributes: 
  - AttributeName: isFraudulent
    AttributeType: BOOL
  - AttributeName: label
    AttributeType: STRING
  Name: imei
  PrimaryId: 
    AttributeName: value
    AttributeType: STRING
    Nullable: false
  VertexId: 5
  VertexStatisticsType: 1
- Attributes: 
  - AttributeName: isFraudulent
    AttributeType: BOOL
  - AttributeName: label
    AttributeType: STRING
  Name: ip
  PrimaryId: 
    AttributeName: value
    AttributeType: STRING
    Nullable: false
  VertexId: 6
  VertexStatisticsType: 1
