EdgeTypes: 
- Attributes: 
  - AttributeName: time
    AttributeType: UINT
  EdgeId: 0
  EdgeName: e_thru
  FromVertexTypeName: v_ip
  IsDirected: false
  ToVertexTypeName: v_session
GraphConfigVersion: 1
GraphId: 0
GraphName: poc_graph
SegSizeInBits: 20
VertexTypes: 
- PrimaryId: 
    AttributeName: ip
    AttributeType: STRING
  VertexId: 0
  VertexName: v_ip
  VertexStatisticsType: 1
- PrimaryId: 
    AttributeName: sid
    AttributeType: STRING
  VertexId: 1
  VertexName: v_session
  VertexStatisticsType: 1
