EdgeTypes: 
- EdgeId: 0
  EdgeName: transtoentity
  FromVertexTypeName: '*'
  IsDirected: false
  ToVertexTypeName: '*'
GraphConfigVersion: 1
GraphId: 0
GraphName: lianlian
SegSizeInBits: 20
VertexTypes: 
- Attributes: 
  - AttributeName: isFraudulent
    AttributeType: BOOL
  PrimaryId: 
    AttributeName: value
    AttributeType: STRING
    Nullable: false
  VertexId: 0
  VertexName: transaction
  VertexStatisticsType: 1
- Attributes: 
  - AttributeName: isFraudulent
    AttributeType: BOOL
  PrimaryId: 
    AttributeName: value
    AttributeType: STRING
    Nullable: false
  VertexId: 1
  VertexName: userid
  VertexStatisticsType: 1
- Attributes: 
  - AttributeName: isFraudulent
    AttributeType: BOOL
  PrimaryId: 
    AttributeName: value
    AttributeType: STRING
    Nullable: false
  VertexId: 2
  VertexName: ssn
  VertexStatisticsType: 1
- Attributes: 
  - AttributeName: isFraudulent
    AttributeType: BOOL
  PrimaryId: 
    AttributeName: value
    AttributeType: STRING
    Nullable: false
  VertexId: 3
  VertexName: bankid
  VertexStatisticsType: 1
- Attributes: 
  - AttributeName: isFraudulent
    AttributeType: BOOL
  PrimaryId: 
    AttributeName: value
    AttributeType: STRING
    Nullable: false
  VertexId: 4
  VertexName: cell
  VertexStatisticsType: 1
- Attributes: 
  - AttributeName: isFraudulent
    AttributeType: BOOL
  PrimaryId: 
    AttributeName: value
    AttributeType: STRING
    Nullable: false
  VertexId: 5
  VertexName: imei
  VertexStatisticsType: 1
- Attributes: 
  - AttributeName: isFraudulent
    AttributeType: BOOL
  PrimaryId: 
    AttributeName: value
    AttributeType: STRING
    Nullable: false
  VertexId: 6
  VertexName: ip
  VertexStatisticsType: 1
