AttributeEnumerators: 1
EdgeTypes: 
- Attributes: 
  - AttributeName: role
    AttributeType: STRING
  EdgeId: 0
  FromVertexTypeName: person
  InitVersionAttributes: 
  - AttributeName: role
    AttributeType: STRING
  IsDirected: true
  Name: roles
  ToVertexTypeName: movie
GraphConfigVersion: 1
GraphId: 0
GraphName: person_movie
SegSizeInBits: 20
VertexTypes: 
- Attributes: 
  - AttributeName: name
    AttributeType: STRING
  InitVersionAttributes: 
  - AttributeName: name
    AttributeType: STRING
  Name: person
  PrimaryId: 
    AttributeName: id
    AttributeType: UINT
  SecondaryIds: 
  - AttributeName: sid
    AttributeType: UINT
  VertexId: 0
  VertexStatisticsType: 1
- Attributes: 
  - AttributeName: title
    AttributeType: STRING
  - AttributeName: country
    AttributeType: UINT
    Enumerator: 1
  - AttributeName: year
    AttributeType: UINT
  InitVersionAttributes: 
  - AttributeName: title
    AttributeType: STRING
  - AttributeName: country
    AttributeType: UINT
    Enumerator: 2147483647
  - AttributeName: year
    AttributeType: UINT
  Name: movie
  PrimaryId: 
    AttributeName: id
    AttributeType: UINT
  VertexId: 1
  VertexStatisticsType: 1
