# -*- mode: python; -*-
#  Customers gperun
Import('env')

# TODO: 
if int(ARGUMENTS.get('use_zmq', 0)) == 1:
    env.Append(CPPDEFINES={'USE_ZMQ':1})

src_files = Split("""gperun.cpp
                     gpeconfig.cpp
                     enginejoblistener.cpp
                     enginejobrunner.cpp
                     enginejobrunner_zmq.cpp
                     ../../../core/gse/gse2/dict/enum/RedisEnumeratorClient.cpp
                     ../../core_impl/udt.cpp
				  """)

gperun_server_build = env.Program(target='poc_gpe_server', 
						source=src_files)
Return ("gperun_server_build")
