# -*- mode: python; -*-
#  GPERUN

#                    dq/dq_2t.cpp

Import('env')
src_files = Split("""
                    distributed/dist_basic.cpp
                    dqss/dqss_basic.cpp
                    perf/threadpool_test.cpp
                    unit_main.cpp
                    gpe4/test_gpe4_udf.cpp
                    gpe4/test_topology_delta.cpp
                    util/test_util.cpp
                  """
                  )
unittest_build = env.Program(target='gunit', source=src_files)
Return ("unittest_build")
