SegSizeInBits: 20   # partition segment size in bit, default is 2^20 or 1 million
GraphName: "SimpleWeightedGraph" 
GraphID: 0          # when give 0, GSE will automatically assign the next ID to this graph
AttributeEnumerators: 0  # total number of enumerators used by vertex and edge attributes
VertexTypes:
  - id: 0           # no type, put 0 here
    typename: "vtype_dummy"
    attributes:     # attribute order matters.
EdgeTypes:
  - id: 0               # no type, put 0 here.
    typename: "etype_dummy"
    isdirected: false   # per this type
    attributes:
      - type: "INT"
        name: "weight"
        nullable: false
