# -*- mode: python; -*-
#  GPERUN

Import('env')
src_files = Split("""
                    core_ext/test_ext_gpe.cpp
                    core_ext/test_ext_gse.cpp
                    core_impl/test_impl_gpe.cpp
                    core_impl/test_impl_gse.cpp
                    unit_main.cpp
                  """
                  )
unittest_build = env.Program(target='gunit', source=src_files)
Return ("unittest_build")
